### ISSUE TITLE
So sorry to reach out to you through here!

### ISSUE THREAD

**Issue by derto42** [VictoriaLind/PyQt5-Screen-Color-Picker_v1#1]
Unfortunately github doesn't have messages so I hope this is okay.

I am looking for anyone who has shown recent interest in PyQt5.

Me and a couple of other people are working on a productivity tool using PyQt5. Our goal is to create something that hundreds of people would find useful. I actually have been wanting to make a color picker app for my personal use and I stumbled upon this. Would you be interested in combining powers on this? I would love for the color picker to become a plugin for the productivity tool we are working on. There will be some other graphic design tools I will implement as well.
 
https://github.com/derto42/FlowBuddy

Here is my discord as well if interested: https://discord.gg/ahvpBbXG

**Comment by Vicky-Lind** [comment]
@derto42 

Hi, thank you for reaching out 👋
I appreciate the invite, but honestly all my program does is that it just opens the default PyQt dialog called "QColorDialog". I made this so that I could easily and quickly open a screen color picker (+ as a small "project"). 

Really like your FlowBuddy idea and will for sure be using it!

**Comment by derto42** [comment]
Absolutely!

Quick ColorPicker app is one of the features I wanted to implement in FlowBuddy for a long time.

I am a graphic designer and I definitely need this feature every day :) 

Well come join our discord, we do have a list of potential ideas on there. If any of them seem interesting - feel free to try and make them. 

https://discord.gg/2XqbYVJn
